name: Build datastore container

on:
  workflow_call:
    inputs:
      cnt_suffix:
        required: false
        type: string
    secrets:
      cr_pat:
        required: true
jobs:
  build_containers:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Get Previous tag
        id: current_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0
              
      # Set Github Access Token with "write:packages & read:packages" scope for Github Container Registry.
      # Then go to repository setings and add the copied token as a secret called "CR_PAT"
      # https://github.com/settings/tokens/new?scopes=repo,write:packages&description=Github+Container+Registry
      # ! While GHCR is in Beta make sure to enable the feature
      - name: Logging into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.cr_pat }}

      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v2

      - name: Build and push datastore to Github Container Registry
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}${{ inputs.cnt_suffix }}:${{ github.sha }},ghcr.io/${{ github.repository }}${{ inputs.cnt_suffix }}:${{steps.current_tag.outputs.tag}},ghcr.io/${{ github.repository }}${{ inputs.cnt_suffix }}:latest

