name: Docker Image CI

on:
  push:
    branches: [ master, main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Publish Image
      uses: matootie/github-docker@v3.1.0
      id: publish
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        tag: |
          latest
          ${{ github.sha }}

    - name: Print Full Image URL
      run: echo ${{ steps.publish.outputs.imageURL }}:${{ github.sha }}