name: Auto Build docker image

on:
  push:
    tags:
      - "*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initialize mandatory git config
      run: |
        git config user.name "GitHub Actions"
        git config user.email noreply@github.com
    - name: Read release version information
      run: |
        versionName=`sed '1q;d' versions.txt | cut -d "=" -f2 | xargs`
        export VERSION_NAME=$versionName
        echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

    - name: Publish Image
      uses: matootie/github-docker@v3.1.0
      id: publish
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        tag: |
          v${{ env.VERSION_NAME }}
          latest
          ${{ github.sha }}

    - name: Print Full Image URL
      run: echo ${{ steps.publish.outputs.imageURL }}:${{ github.sha }}